#[build]
#  base    = "/"
#  publish = "search/"
#[build]
#  command = "npm run build"
#  publish="dist"
#  base = "/"

[[redirects]]
  from = "/*"
  to = "/search/:splat"
  status = 200
  
  [[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
